services:
  laboratory-management-api:
    image: ${DOCKER_REGISTRY-}laboratorymanagementapi
    build:
      context: .
      dockerfile: src/API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=PddlDb;Username=postgres;Password=postgres"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    container_name: pddl-postgres
    environment:
      POSTGRES_DB: PddlDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PddlDb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: