<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\ActivityLog\Commands\" />
    <Folder Include="Features\AdministratorProfile\" />
    <Folder Include="Features\ClinicalStaffProfile\" />
    <Folder Include="Features\RefreshToken\" />
    <Folder Include="Features\SystemConfig\" />
    <Folder Include="Features\StorageStatus\" />
    <Folder Include="Features\PatientProfile\" />
    <Folder Include="Features\SmsGateway\" />
    <Folder Include="Features\Notification\" />
  </ItemGroup>

</Project>
